files = main.cpp
files += engine.cpp engine.hpp
files += parser.cpp parser.hpp
files += player.cpp player.hpp
files += item.cpp item.hpp
files += roomhandler.cpp roomhandler.hpp
files += room.cpp room.hpp

all:
	g++ -std=c++11 $(files)

clean:
	rm *.hpp.gch
	rm *.out